package it.unipd.mtss;

import static org.junit.Assert.assertEquals;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.Arrays;
import java.util.Collection;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class RomanNumber_MainParameterizedTest{

    private String [] input={"test"};
    private String output;

    public RomanNumber_MainParameterizedTest(String input,String output)
    {
        this.input[0]=input;
        this.output=output;
    }

    @Parameters
    public static Collection<Object[]> Input_Output()
    {
        return Arrays.asList(new Object[][]{{"1"," ____ \n" + 
                                                 "|    |\n" + 
                                                 " |  | \n" +
                                                 " |  | \n" +
                                                 " |  | \n" +
                                                 "|____|\n"},   {"2", " ____  ____ \n" +
                                                                      "|    ||    |\n" +
                                                                      " |  |  |  | \n" +
                                                                      " |  |  |  | \n" +
                                                                      " |  |  |  | \n" +
                                                                      "|____||____|\n"}, {"3"," ____  ____  ____ \n" + 
                                                                                             "|    ||    ||    |\n" + 
                                                                                             " |  |  |  |  |  | \n" + 
                                                                                             " |  |  |  |  |  | \n" + 
                                                                                             " |  |  |  |  |  | \n" + 
                                                                                             "|____||____||____|\n"}, {"4"," ____ __      __\n" +
                                                                                                                           "|    |\\ \\    / /\n" +
                                                                                                                           " |  |  \\ \\  / / \n" +
                                                                                                                           " |  |   \\ \\/ /  \n" +
                                                                                                                           " |  |    \\  /   \n" +
                                                                                                                           "|____|    \\/    \n"}, {"6","__      __ ____ \n" +
                                                                                                                                                      "\\ \\    / /|    |\n" +
                                                                                                                                                      " \\ \\  / /  |  | \n" +
                                                                                                                                                      "  \\ \\/ /   |  | \n" +
                                                                                                                                                      "   \\  /    |  | \n" +
                                                                                                                                                      "    \\/    |____|\n"},{"9"," ____ __   __\n"+
                                                                                                                                                                                  "|    |\\ \\ / /\n"+
                                                                                                                                                                                  " |  |  \\ V / \n"+
                                                                                                                                                                                  " |  |   > <  \n"+
                                                                                                                                                                                  " |  |  / . \\ \n"+
                                                                                                                                                                                  "|____||_/ \\_|\n"},{"10","__   __\n"+
                                                                                                                                                                                                            "\\ \\ / /\n"+
                                                                                                                                                                                                            " \\ V / \n"+
                                                                                                                                                                                                            "  > <  \n"+
                                                                                                                                                                                                            " / . \\ \n"+
                                                                                                                                                                                                            "|_/ \\_|\n"},{"11","__   __ ____ \n" + 
                                                                                                                                                                                                                          "\\ \\ / /|    |\n" + 
                                                                                                                                                                                                                          " \\ V /  |  | \n" + 
                                                                                                                                                                                                                          "  > <   |  | \n" + 
                                                                                                                                                                                                                          " / . \\  |  | \n" +
                                                                                                                                                                                                                          "|_/ \\_||____|\n"},{"15","__   ____      __\n" + 
                                                                                                                                                                                                                                                "\\ \\ / /\\ \\    / /\n" + 
                                                                                                                                                                                                                                                " \\ V /  \\ \\  / / \n" + 
                                                                                                                                                                                                                                                "  > <    \\ \\/ /  \n" + 
                                                                                                                                                                                                                                                " / . \\    \\  /   \n" + 
                                                                                                                                                                                                                                                "|_/ \\_|    \\/    \n"},{"19","__   __ ____ __   __\n" + 
                                                                                                                                                                                                                                                                             "\\ \\ / /|    |\\ \\ / /\n" + 
                                                                                                                                                                                                                                                                             " \\ V /  |  |  \\ V / \n" + 
                                                                                                                                                                                                                                                                             "  > <   |  |   > <  \n" + 
                                                                                                                                                                                                                                                                             " / . \\  |  |  / . \\ \n" + 
                                                                                                                                                                                                                                                                             "|_/ \\_||____||_/ \\_|\n"},{"20","__   ____   __\n" + 
                                                                                                                                                                                                                                                                                                            "\\ \\ / /\\ \\ / /\n" + 
                                                                                                                                                                                                                                                                                                            " \\ V /  \\ V / \n" + 
                                                                                                                                                                                                                                                                                                            "  > <    > <  \n" + 
                                                                                                                                                                                                                                                                                                            " / . \\  / . \\ \n" +
                                                                                                                                                                                                                                                                                                            "|_/ \\_||_/ \\_|\n"},{"27","__   ____   ____      __ ____  ____ \n"+ 
                                                                                                                                                                                                                                                                                                                                        "\\ \\ / /\\ \\ / /\\ \\    / /|    ||    |\n"+
                                                                                                                                                                                                                                                                                                                                        " \\ V /  \\ V /  \\ \\  / /  |  |  |  | \n"+
                                                                                                                                                                                                                                                                                                                                        "  > <    > <    \\ \\/ /   |  |  |  | \n"+
                                                                                                                                                                                                                                                                                                                                        " / . \\  / . \\    \\  /    |  |  |  | \n"+ 
                                                                                                                                                                                                                                                                                                                                        "|_/ \\_||_/ \\_|    \\/    |____||____|\n"},{"39","__   ____   ____   __ ____ __   __\n" + 
                                                                                                                                                                                                                                                                                                                                                                                           "\\ \\ / /\\ \\ / /\\ \\ / /|    |\\ \\ / /\n" + 
                                                                                                                                                                                                                                                                                                                                                                                           " \\ V /  \\ V /  \\ V /  |  |  \\ V / \n" + 
                                                                                                                                                                                                                                                                                                                                                                                           "  > <    > <    > <   |  |   > <  \n" + 
                                                                                                                                                                                                                                                                                                                                                                                           " / . \\  / . \\  / . \\  |  |  / . \\ \n" +
                                                                                                                                                                                                                                                                                                                                                                                           "|_/ \\_||_/ \\_||_/ \\_||____||_/ \\_|\n"},{"40","__   __  _    \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                             "\\ \\ / / | |   \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                             " \\ V /  | |   \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                             "  > <   | |   \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                             " / . \\  | |__ \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                             "|_/ \\_| |____|\n"},{"50","  _    \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " | |   \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " | |   \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " | |   \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " | |__ \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " |____|\n"},{"99","__   __  ____  ____ __   __\n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "\\ \\ / / / ___||    |\\ \\ / /\n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " \\ V / | |     |  |  \\ V / \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "  > <  | |     |  |   > <  \n" + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " / . \\ | |___  |  |  / . \\ \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "|_/ \\_| \\____||____||_/ \\_|\n"},{"100","  ____ \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       " / ___|\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "| |    \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "| |    \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "| |___ \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       " \\____|\n"},{"499","  ____  _____  __   __  ____  ____ __   __\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " / ___||  __ \\ \\ \\ / / / ___||    |\\ \\ / /\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "| |    | |  | | \\ V / | |     |  |  \\ V / \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "| |    | |  | |  > <  | |     |  |   > <  \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "| |___ | |__| | / . \\ | |___  |  |  / . \\ \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " \\____||_____/ |_/ \\_| \\____||____||_/ \\_|\n"},{"500"," _____  \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "|  __ \\ \n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "| |  | |\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "| |  | |\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "| |__| |\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "|_____/ \n"}});
    }
    @Before
    public void printExecution()
    {
        System.out.printf("Executing parameterized test (Main)\n");
    }

    @Test
    public void TestNormalInput() throws NoParamException, NoValidParamException, EqualsZeroException, NegativeNumberException
    {
        System.out.printf("Testing Main with %s as input\n",input[0]);
        ByteArrayOutputStream OutputCatcher = new ByteArrayOutputStream();
        System.setOut(new PrintStream(OutputCatcher));
        RomanNumber.main(input);
        assertEquals(output,OutputCatcher.toString());
    }

    
}
